<a href="https://colab.research.google.com/github/VsAthul/Fun-with-Jupyter/blob/main/test_db.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect('test_db')

In [3]:
cursor_obj= conn.cursor()

In [17]:
table=""" create table instructor(id int primary key not null, fname varchar(20), lname varchar(20), city varchar(10), ccode char(2))"""
cursor_obj.execute(table)
print("Table is ready")

OperationalError: table instructor already exists

In [8]:
cursor_obj.execute(''' insert into instructor values(1, 'Rav', 'Ahuja', 'TORONTO', 'CA'), (2, 'Raul', 'Chong', 'Markham', 'CA'), (3, 'Hima', 'Vasudevan', 'Chicago', 'US') ''')

In [35]:
statement=""" select * from instructor """
cursor_obj.execute(statement)
print("All the data")
outputall=cursor_obj.fetchall()
print(outputall)
for row in outputall:
  print(row)

ProgrammingError: Cannot operate on a closed database.

In [12]:
import pandas as pd

In [36]:
df=pd.read_sql_query("select * from instructor",conn)
df

ProgrammingError: Cannot operate on a closed database.

In [30]:
df.loc[3]=[4,"athul","vs","amk",'BH']
df

   id  fname      lname     city ccode
0   1    Rav      Ahuja  TORONTO    CA
1   2   Raul      Chong  Markham    CA
2   3   Hima  Vasudevan  Chicago    US
3   4  athul         vs      amk    BH

In [32]:
new_row = pd.DataFrame({"id":[5],"fname":["amal"],"lname":["vs"],"city":["ktm"],"ccode":["IN"]})

In [33]:
df=pd.concat([df,new_row], ignore_index=True)
df

   id  fname      lname     city ccode
0   1    Rav      Ahuja  TORONTO    CA
1   2   Raul      Chong  Markham    CA
2   3   Hima  Vasudevan  Chicago    US
3   4  athul         vs      amk    BH
4   5   amal         vs      ktm    IN

In [34]:
conn.close()